version: '3'
services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: your_password
      MONGO_INITDB_DATABASE: dota2
    volumes:
      - mongo-data:/data/db
    networks:
      - dota2-network
  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: your_password
      ME_CONFIG_MONGODB_DATABASE: dota2
      ME_CONFIG_MONGODB_SERVER: db
    ports:
      - "8081:8081"
    networks:
      - dota2-network
  flask-app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
      - mongo-express
    networks:
      - dota2-network
networks:
  dota2-network:

volumes:
  mongo-data:
